In [1]:
import pandas as pd

In [2]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../scripts')))

In [3]:
from RFMSScore import *
from plottings import *

In [4]:
df = pd.read_csv('../assets/data/processed_dataa.csv')

In [5]:
df.head()

,index,TransactionId,CustomerId,Amount,TransactionStartTime,PricingStrategy,FraudResult,TotalTransactionAmount,AverageTransactionAmount,TotalTransactions,...,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill,ChannelId_ChannelId_1,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5
0,0,TransactionId_76871,CustomerId_4406,1000.0,2018-11-15 02:18:49+00:00,2,0,109921.75,923.712185,-0.311831,...,0,0,0,0,0,0,0,0,1,0
1,1,TransactionId_73770,CustomerId_4406,-20.0,2018-11-15 02:19:08+00:00,2,0,109921.75,923.712185,-0.311831,...,0,0,0,0,0,0,0,1,0,0
2,2,TransactionId_26203,CustomerId_4683,500.0,2018-11-15 02:44:21+00:00,2,0,1000.00,500.000000,-0.444993,...,0,0,0,0,0,0,0,0,1,0
3,3,TransactionId_380,CustomerId_988,20000.0,2018-11-15 03:32:55+00:00,2,0,228727.20,6019.136842,-0.404020,...,0,0,0,0,0,1,0,0,1,0
4,4,TransactionId_28195,CustomerId_988,-644.0,2018-11-15 03:34:21+00:00,2,0,228727.20,6019.136842,-0.404020,...,0,0,0,0,0,0,0,1,0,0

In [6]:
df.columns

Index(['index', 'TransactionId', 'CustomerId', 'Amount',
       'TransactionStartTime', 'PricingStrategy', 'FraudResult',
       'TotalTransactionAmount', 'AverageTransactionAmount',
       'TotalTransactions', 'StdTransactionAmount', 'TransactionHour',
       'TransactionDay', 'TransactionMonth', 'TransactionYear',
       'ProductCategory_airtime', 'ProductCategory_data_bundles',
       'ProductCategory_financial_services', 'ProductCategory_movies',
       'ProductCategory_other', 'ProductCategory_ticket',
       'ProductCategory_transport', 'ProductCategory_tv',
       'ProductCategory_utility_bill', 'ChannelId_ChannelId_1',
       'ChannelId_ChannelId_2', 'ChannelId_ChannelId_3',
       'ChannelId_ChannelId_5'],
      dtype='object')

In [7]:
RFMS = RFMSCalculator(df)

In [8]:
df_rfms = RFMS.calculate_rfms()

In [9]:
df_rfms.head()

,index,TransactionId,CustomerId,Amount,TransactionStartTime,PricingStrategy,FraudResult,TotalTransactionAmount,AverageTransactionAmount,TotalTransactions,...,ProductCategory_tv,ProductCategory_utility_bill,ChannelId_ChannelId_1,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5,Recency,Frequency,Monetary,RFMS_Label
0,0,TransactionId_76871,CustomerId_4406,1000.0,2018-11-15 02:18:49+00:00,2,0,109921.75,923.712185,-0.311831,...,0,0,0,0,1,0,90,119,109921.75,1
1,1,TransactionId_73770,CustomerId_4406,-20.0,2018-11-15 02:19:08+00:00,2,0,109921.75,923.712185,-0.311831,...,0,0,0,1,0,0,90,119,109921.75,1
2,2,TransactionId_26203,CustomerId_4683,500.0,2018-11-15 02:44:21+00:00,2,0,1000.00,500.000000,-0.444993,...,0,0,0,0,1,0,90,2,1000.00,1
3,3,TransactionId_380,CustomerId_988,20000.0,2018-11-15 03:32:55+00:00,2,0,228727.20,6019.136842,-0.404020,...,0,1,0,0,1,0,90,38,228727.20,1
4,4,TransactionId_28195,CustomerId_988,-644.0,2018-11-15 03:34:21+00:00,2,0,228727.20,6019.136842,-0.404020,...,0,0,0,1,0,0,90,38,228727.20,1

In [10]:
label = Labeling(df_rfms)

In [11]:
label.assign_good_bad_labels()

,index,TransactionId,CustomerId,Amount,TransactionStartTime,PricingStrategy,FraudResult,TotalTransactionAmount,AverageTransactionAmount,TotalTransactions,...,ProductCategory_utility_bill,ChannelId_ChannelId_1,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5,Recency,Frequency,Monetary,RFMS_Label,User_Label
0,0,TransactionId_76871,CustomerId_4406,1000.0,2018-11-15 02:18:49+00:00,2,0,109921.75,923.712185,-0.311831,...,0,0,0,1,0,90,119,109921.75,1,Bad
1,1,TransactionId_73770,CustomerId_4406,-20.0,2018-11-15 02:19:08+00:00,2,0,109921.75,923.712185,-0.311831,...,0,0,1,0,0,90,119,109921.75,1,Bad
2,2,TransactionId_26203,CustomerId_4683,500.0,2018-11-15 02:44:21+00:00,2,0,1000.00,500.000000,-0.444993,...,0,0,0,1,0,90,2,1000.00,1,Bad
3,3,TransactionId_380,CustomerId_988,20000.0,2018-11-15 03:32:55+00:00,2,0,228727.20,6019.136842,-0.404020,...,1,0,0,1,0,90,38,228727.20,1,Bad
4,4,TransactionId_28195,CustomerId_988,-644.0,2018-11-15 03:34:21+00:00,2,0,228727.20,6019.136842,-0.404020,...,0,0,1,0,0,90,38,228727.20,1,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,95657,TransactionId_89881,CustomerId_3078,-1000.0,2019-02-13 09:54:09+00:00,2,0,2438140.00,4255.043630,0.204885,...,0,0,1,0,0,0,573,2438140.00,0,Good
95658,95658,TransactionId_91597,CustomerId_3874,1000.0,2019-02-13 09:54:25+00:00,2,0,58499.60,1360.455814,-0.398330,...,0,0,0,1,0,0,43,58499.60,1,Bad
95659,95659,TransactionId_82501,CustomerId_3874,-20.0,2019-02-13 09:54:35+00:00,2,0,58499.60,1360.455814,-0.398330,...,0,0,1,0,0,0,43,58499.60,1,Bad
95660,95660,TransactionId_136354,CustomerId_1709,3000.0,2019-02-13 10:01:10+00:00,2,0,851985.00,1625.925573,0.149116,...,0,0,0,1,0,0,524,851985.00,0,Good
95661,95661,TransactionId_35670,CustomerId_1709,-60.0,2019-02-13 10:01:28+00:00,2,0,851985.00,1625.925573,0.149116,...,0,0,1,0,0,0,524,851985.00,0,Good

In [12]:
df_rfms.tail(10)

,index,TransactionId,CustomerId,Amount,TransactionStartTime,PricingStrategy,FraudResult,TotalTransactionAmount,AverageTransactionAmount,TotalTransactions,...,ProductCategory_utility_bill,ChannelId_ChannelId_1,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5,Recency,Frequency,Monetary,RFMS_Label,User_Label
95652,95652,TransactionId_71994,CustomerId_960,1700.0,2019-02-13 09:50:20+00:00,2,0,120795.0,2745.340909,-0.397192,...,0,0,0,1,0,0,44,120795.0,1,Bad
95653,95653,TransactionId_68851,CustomerId_539,-140.0,2019-02-13 09:50:34+00:00,2,0,22610.0,1413.125000,-0.429059,...,0,0,1,0,0,0,16,22610.0,1,Bad
95654,95654,TransactionId_18130,CustomerId_960,1000.0,2019-02-13 09:52:31+00:00,2,0,120795.0,2745.340909,-0.397192,...,0,0,0,1,0,0,44,120795.0,1,Bad
95655,95655,TransactionId_38907,CustomerId_960,-50.0,2019-02-13 09:52:49+00:00,2,0,120795.0,2745.340909,-0.397192,...,0,0,1,0,0,0,44,120795.0,1,Bad
95656,95656,TransactionId_68402,CustomerId_3078,50000.0,2019-02-13 09:53:55+00:00,2,0,2438140.0,4255.043630,0.204885,...,0,0,0,1,0,0,573,2438140.0,0,Good
95657,95657,TransactionId_89881,CustomerId_3078,-1000.0,2019-02-13 09:54:09+00:00,2,0,2438140.0,4255.043630,0.204885,...,0,0,1,0,0,0,573,2438140.0,0,Good
95658,95658,TransactionId_91597,CustomerId_3874,1000.0,2019-02-13 09:54:25+00:00,2,0,58499.6,1360.455814,-0.398330,...,0,0,0,1,0,0,43,58499.6,1,Bad
95659,95659,TransactionId_82501,CustomerId_3874,-20.0,2019-02-13 09:54:35+00:00,2,0,58499.6,1360.455814,-0.398330,...,0,0,1,0,0,0,43,58499.6,1,Bad
95660,95660,TransactionId_136354,CustomerId_1709,3000.0,2019-02-13 10:01:10+00:00,2,0,851985.0,1625.925573,0.149116,...,0,0,0,1,0,0,524,851985.0,0,Good
95661,95661,TransactionId_35670,CustomerId_1709,-60.0,2019-02-13 10:01:28+00:00,2,0,851985.0,1625.925573,0.149116,...,0,0,1,0,0,0,524,851985.0,0,Good

In [14]:
df_rfms.to_csv('../assets/data/RFMScore.csv', index=False)

In [15]:
df_rfms

,index,TransactionId,CustomerId,Amount,TransactionStartTime,PricingStrategy,FraudResult,TotalTransactionAmount,AverageTransactionAmount,TotalTransactions,...,ProductCategory_utility_bill,ChannelId_ChannelId_1,ChannelId_ChannelId_2,ChannelId_ChannelId_3,ChannelId_ChannelId_5,Recency,Frequency,Monetary,RFMS_Label,User_Label
0,0,TransactionId_76871,CustomerId_4406,1000.0,2018-11-15 02:18:49+00:00,2,0,109921.75,923.712185,-0.311831,...,0,0,0,1,0,90,119,109921.75,1,Bad
1,1,TransactionId_73770,CustomerId_4406,-20.0,2018-11-15 02:19:08+00:00,2,0,109921.75,923.712185,-0.311831,...,0,0,1,0,0,90,119,109921.75,1,Bad
2,2,TransactionId_26203,CustomerId_4683,500.0,2018-11-15 02:44:21+00:00,2,0,1000.00,500.000000,-0.444993,...,0,0,0,1,0,90,2,1000.00,1,Bad
3,3,TransactionId_380,CustomerId_988,20000.0,2018-11-15 03:32:55+00:00,2,0,228727.20,6019.136842,-0.404020,...,1,0,0,1,0,90,38,228727.20,1,Bad
4,4,TransactionId_28195,CustomerId_988,-644.0,2018-11-15 03:34:21+00:00,2,0,228727.20,6019.136842,-0.404020,...,0,0,1,0,0,90,38,228727.20,1,Bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,95657,TransactionId_89881,CustomerId_3078,-1000.0,2019-02-13 09:54:09+00:00,2,0,2438140.00,4255.043630,0.204885,...,0,0,1,0,0,0,573,2438140.00,0,Good
95658,95658,TransactionId_91597,CustomerId_3874,1000.0,2019-02-13 09:54:25+00:00,2,0,58499.60,1360.455814,-0.398330,...,0,0,0,1,0,0,43,58499.60,1,Bad
95659,95659,TransactionId_82501,CustomerId_3874,-20.0,2019-02-13 09:54:35+00:00,2,0,58499.60,1360.455814,-0.398330,...,0,0,1,0,0,0,43,58499.60,1,Bad
95660,95660,TransactionId_136354,CustomerId_1709,3000.0,2019-02-13 10:01:10+00:00,2,0,851985.00,1625.925573,0.149116,...,0,0,0,1,0,0,524,851985.00,0,Good
95661,95661,TransactionId_35670,CustomerId_1709,-60.0,2019-02-13 10:01:28+00:00,2,0,851985.00,1625.925573,0.149116,...,0,0,1,0,0,0,524,851985.00,0,Good